### ISSUE TITLE
Add  .setTimeout() functionality

### ISSUE THREAD

**Issue by calren** [codepath/CPAsyncHttpClient#4]
We can utilize the `setClientTimeout()`  and `setReadTimeout()` from okhttp.  https://stackoverflow.com/questions/25953819/how-to-set-connection-timeout-with-okhttp

This will help mitigate `SocketTimeoutError`s

**Comment by nesquena** [comment]
Good suggestion, this is especially useful for the book lab! @rogerhu would you be able to help with adding this pass through to bring back the setTimeout and releasing a new version?

**Comment by rogerhu** [comment]
I added `setReadTimeout()` and `setConnectTimeout()` to the API with seconds as default.  Can you give it a try?  The new version has been tagged as `2.1.0`.

**Comment by nesquena** [comment]
Thanks Roger! 🙏 

@calren Do you think it is worth adding a setTimeout to mirror the older API which sets both of these at the same time or is this good as is?

**Comment by calren** [comment]
Oh great, I see Roger already added setTimeout() https://github.com/codepath/CPAsyncHttpClient/commit/216b2f647a6aa44d6832e56c7b5d03df4aea39d1 😄 

Thanks Roger!
